#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import math
import sys
import os
from collections import Counter
from typing import Dict, List, Tuple, Optional
import statistics
import json
from datetime import datetime

class AITextAnalyzer:
    """
    Улучшенный анализатор текста для выявления признаков ИИ-генерации
    """
    
    def __init__(self):
        # Расширенные маркеры ИИ с весами
        self.ai_markers = {
            'english': {
                'high': [
                    ('delve', 0.8), ('unveil', 0.7), ('transformative', 0.9),
                    ('leverage', 0.7), ('synergy', 0.8), ('paradigm', 0.7),
                    ('pivotal', 0.6), ('resonate', 0.6), ('embark', 0.5),
                    ('unprecedented', 0.8), ('cutting-edge', 0.7),
                    ('groundbreaking', 0.8), ('revolutionary', 0.7),
                    ('comprehensive', 0.5), ('notable', 0.4), ('crucial', 0.5),
                    ('moreover', 0.6), ('furthermore', 0.6), ('consequently', 0.5),
                    ('additionally', 0.5), ('ultimately', 0.6), ('overall', 0.4),
                    ('accordingly', 0.5), ('explore', 0.4), ('journey', 0.3),
                    ('discover', 0.3), ('insight', 0.5), ('perspective', 0.4),
                    ('framework', 0.6), ('methodology', 0.7), ('implementation', 0.6)
                ],
                'medium': [
                    ('important', 0.3), ('significant', 0.4), ('essential', 0.4),
                    ('various', 0.2), ('multiple', 0.2), ('numerous', 0.2),
                    ('demonstrate', 0.3), ('illustrate', 0.3), ('indicate', 0.3),
                    ('therefore', 0.4), ('thus', 0.3), ('hence', 0.3)
                ]
            },
            'russian': {
                'high': [
                    ('погружение', 0.7), ('трансформационный', 0.9),
                    ('синергия', 0.8), ('парадигма', 0.8), ('революционный', 0.7),
                    ('прорывной', 0.8), ('передовой', 0.6), ('инновационный', 0.7),
                    ('всесторонний', 0.6), ('значительный', 0.5),
                    ('примечательный', 0.5), ('критический', 0.5),
                    ('существенный', 0.5), ('более того', 0.6), ('кроме того', 0.5),
                    ('следовательно', 0.5), ('дополнительно', 0.5),
                    ('в конечном счете', 0.7), ('в целом', 0.4), ('соответственно', 0.5),
                    ('отметим', 0.3), ('подчеркнем', 0.4), ('рассмотрим', 0.3),
                    ('проанализируем', 0.4), ('выделим', 0.3), ('ключевой', 0.5),
                    ('оптимизация', 0.7), ('имплементация', 0.8), ('методология', 0.7)
                ],
                'medium': [
                    ('важный', 0.3), ('значимый', 0.3), ('основной', 0.3),
                    ('различный', 0.2), ('множество', 0.2), ('показывать', 0.3),
                    ('демонстрировать', 0.3), ('следовательно', 0.4),
                    ('поэтому', 0.3), ('таким образом', 0.4)
                ]
            }
        }
        
        # Расширенные шаблоны для водяных знаков с детекцией кодов
        self.watermark_patterns = [
            # Стандартные маркеры
            (r'\[([A-Za-z0-9]{8,})\]', 'Скобки []'),
            (r'\{([A-Za-z0-9]{6,})\}', 'Фигурные скобки {}'),
            (r'<([A-Za-z0-9]{6,})>', 'Угловые скобки <>'),
            (r'#([A-Za-z0-9]{6,})', 'Хеш-тег #'),
            
            # Маркеры ИИ-моделей
            (r'генерировано\s+ИИ\s*[:]?\s*([^\n]*)', 'Генерировано ИИ'),
            (r'создано\s+нейросетью\s*[:]?\s*([^\n]*)', 'Создано нейросетью'),
            (r'generated\s+by\s+AI\s*[:]?\s*([^\n]*)', 'Generated by AI'),
            (r'AI-generated\s*[:]?\s*([^\n]*)', 'AI-generated'),
            
            # Модели ИИ
            (r'chatgpt\s*[:]?\s*([^\n]*)', 'ChatGPT'),
            (r'gpt-(\d+)(?:\s*[:]?\s*([^\n]*))?', 'GPT-{}'),
            (r'claude\s*[:]?\s*([^\n]*)', 'Claude'),
            (r'bard\s*[:]?\s*([^\n]*)', 'Bard'),
            (r'copilot\s*[:]?\s*([^\n]*)', 'Copilot'),
            
            # Специальные маркеры
            (r'<\|([^|]+)\|>', 'Специальный маркер <>|'),
            (r'\[INST\]([^\[]*)\[/INST\]', 'Инструкция [INST]'),
            (r'<s>(.*?)</s>', 'Токен <s>'),
            
            # Эмодзи и символы
            (r'([💬🤖✨🔮🧠💡🎯📊])', 'Эмодзи-маркер'),
            
            # Скрытые маркеры (Unicode)
            (r'[\u200B\u200C\u200D\uFEFF]', 'Невидимый символ'),
            
            # Базовые коды
            (r'([A-F0-9]{32})', 'MD5-хеш'),
            (r'([A-F0-9]{40})', 'SHA1-хеш'),
            (r'([A-Fa-f0-9]{64})', 'SHA256-хеш'),
            (r'([A-Za-z0-9+/]{32,}={0,2})', 'Base64-код'),
        ]
        
        # Пороги для определения переводных текстов
        self.translation_indicators = {
            'common_phrases': [
                (r'\b(?:translation|translator|translate|translated)\b', 0.3),
                (r'\b(?:from|to|in)\s+(?:russian|english|french|german|spanish)\b', 0.2),
                (r'\b(?:google\s*translate|гугл\s*переводчик)\b', 0.5),
                (r'\b(?:machine\s*translation|машинный\s*перевод)\b', 0.4),
            ],
            'unnatural_patterns': [
                (r'\b(?:this|that)\s+(?:is|are)\s+(?:the|a)\s+\w+\s+that\s+', 0.2),
                (r'\b(?:it|they)\s+is\b', 0.3),
                (r'\b(?:have|has)\s+been\s+\w+ed\s+by\b', 0.2),
            ]
        }
        
        # Базовые статистические пороги
        self.thresholds = {
            'perplexity_high': 85,
            'perplexity_medium': 60,
            'burstiness_low': 0.35,
            'burstiness_medium': 0.55,
            'repetition_high': 0.18,
            'repetition_medium': 0.12,
            'entropy_low': 3.8,
            'entropy_medium': 4.5,
            'sentence_length_std': 15,
            'vocabulary_richness': 0.6,
        }
    
    def _calculate_skewness(self, data: List[float]) -> float:
        """
        Ручной расчет асимметрии (skewness) для совместимости с Python < 3.8
        """
        n = len(data)
        if n < 3:
            return 0
        
        mean = sum(data) / n
        
        # Вычисляем центральные моменты
        m2 = sum((x - mean) ** 2 for x in data) / n
        m3 = sum((x - mean) ** 3 for x in data) / n
        
        if m2 == 0:
            return 0
        
        # Коэффициент асимметрии
        skewness = m3 / (m2 ** 1.5)
        
        # Поправка для малых выборок
        if n < 25:
            skewness = skewness * math.sqrt(n * (n - 1)) / (n - 2)
        
        return skewness
    
    def detect_language(self, text: str) -> str:
        """Улучшенное определение языка"""
        clean_text = re.sub(r'[^\w\s]', ' ', text)
        
        cyrillic = len(re.findall(r'[а-яА-ЯёЁ]', clean_text))
        latin = len(re.findall(r'[a-zA-Z]', clean_text))
        
        if cyrillic > latin * 1.2:
            return 'russian'
        elif latin > cyrillic * 1.2:
            return 'english'
        else:
            words = clean_text.lower().split()
            
            lang_markers = {
                'russian': ['и', 'в', 'на', 'с', 'по', 'для', 'от', 'из', 'не', 'что'],
                'english': ['the', 'to', 'and', 'for', 'of', 'with', 'on', 'at', 'from', 'by']
            }
            
            scores = {}
            for lang, markers in lang_markers.items():
                score = sum(1 for w in words if w in markers)
                scores[lang] = score / len(words) if words else 0
            
            return max(scores, key=scores.get) if scores else 'english'
    
    def analyze_translation_indicators(self, text: str) -> Tuple[float, List[str]]:
        """Анализ признаков машинного перевода"""
        text_lower = text.lower()
        found_indicators = []
        score = 0
        
        for pattern, weight in self.translation_indicators['common_phrases']:
            if re.search(pattern, text_lower):
                found_indicators.append(f"Перевод: {pattern}")
                score += weight
        
        for pattern, weight in self.translation_indicators['unnatural_patterns']:
            if re.search(pattern, text_lower):
                found_indicators.append(f"Неестественный паттерн: {pattern}")
                score += weight
        
        words = text.split()
        if len(words) > 10:
            avg_word_len = sum(len(w) for w in words) / len(words)
            if avg_word_len > 6.5:
                score += 0.2
                found_indicators.append(f"Средняя длина слова: {avg_word_len:.1f} (характерно для перевода)")
        
        return min(score, 1.0), found_indicators
    
    def analyze_perplexity(self, text: str) -> float:
        """Улучшенный анализ перплексии"""
        words = text.lower().split()
        if len(words) < 5:
            return 0
        
        ngram_counts = {}
        for n in range(1, 4):
            ngrams = [' '.join(words[i:i+n]) for i in range(len(words)-n+1)]
            ngram_counts[n] = Counter(ngrams)
        
        total_log_prob = 0
        total_count = 0
        
        for n in range(2, 4):
            if len(ngram_counts[n]) > 0:
                for ngram, count in list(ngram_counts[n].items())[:100]:
                    parts = ngram.split()
                    if n > 1:
                        prefix = ' '.join(parts[:-1])
                        prefix_count = ngram_counts[n-1].get(prefix, 0)
                        prob = (count + 1) / (prefix_count + len(ngram_counts[n-1]))
                    else:
                        prob = count / len(words)
                    
                    if prob > 0:
                        total_log_prob += -math.log2(prob)
                        total_count += 1
        
        if total_count == 0:
            return 100
        
        perplexity = 2 ** (total_log_prob / total_count)
        return min(perplexity, 200)
    
    def analyze_burstiness(self, text: str) -> float:
        """Улучшенный анализ вариативности"""
        sentences = re.split(r'[.!?]+', text)
        sentences = [s.strip() for s in sentences if len(s.strip()) > 0]
        
        if len(sentences) < 3:
            return 0
        
        lengths = [len(s.split()) for s in sentences]
        
        if len(lengths) > 1:
            mean_len = statistics.mean(lengths)
            std_len = statistics.stdev(lengths)
            
            cv = std_len / mean_len if mean_len > 0 else 0
            
            # Используем ручной расчет skewness
            skew = self._calculate_skewness(lengths)
            
            burstiness = (cv * 0.7 + abs(skew) * 0.3)
            return min(burstiness, 2.0)
        
        return 0
    
    def analyze_repetition(self, text: str) -> float:
        """Улучшенный анализ повторяемости"""
        words = text.lower().split()
        if len(words) < 10:
            return 0
        
        word_freq = Counter(words)
        
        repeated_words = sum(1 for count in word_freq.values() if count > 1)
        word_repetition = repeated_words / len(word_freq) if word_freq else 0
        
        phrase_repetitions = []
        for n in [2, 3]:
            phrases = [' '.join(words[i:i+n]) for i in range(len(words)-n+1)]
            phrase_freq = Counter(phrases)
            repeated_phrases = sum(1 for count in phrase_freq.values() if count > 1)
            if phrase_freq:
                phrase_repetitions.append(repeated_phrases / len(phrase_freq))
        
        avg_phrase_repetition = statistics.mean(phrase_repetitions) if phrase_repetitions else 0
        
        sentence_starts = []
        sentences = re.split(r'[.!?]+', text)
        for sent in sentences[:20]:
            words_in_sent = sent.strip().split()
            if words_in_sent:
                sentence_starts.append(words_in_sent[0].lower())
        
        start_freq = Counter(sentence_starts)
        start_repetition = sum(1 for count in start_freq.values() if count > 1) / len(start_freq) if start_freq else 0
        
        repetition = (word_repetition * 0.4 + avg_phrase_repetition * 0.4 + start_repetition * 0.2)
        return min(repetition, 1.0)
    
    def analyze_vocabulary_richness(self, text: str) -> float:
        """Анализ богатства словарного запаса"""
        words = text.lower().split()
        if len(words) < 10:
            return 0
        
        unique_words = len(set(words))
        total_words = len(words)
        
        richness = unique_words / total_words
        
        if total_words > 100:
            richness = richness * (1 + math.log10(100 / total_words))
        
        return max(0, min(richness, 1.0))
    
    def detect_ai_markers(self, text: str, lang: str) -> Tuple[float, List[str]]:
        """Улучшенное обнаружение маркеров ИИ с весами"""
        text_lower = text.lower()
        found_markers = []
        total_weight = 0
        max_weight = 0
        
        markers_data = self.ai_markers.get(lang, {})
        
        for category in ['high', 'medium']:
            markers = markers_data.get(category, [])
            for marker, weight in markers:
                if marker in text_lower:
                    found_markers.append(f"{marker} (вес: {weight})")
                    total_weight += weight
            
            max_weight += sum(weight for _, weight in markers) * 0.3
        
        if max_weight > 0:
            marker_score = min(total_weight / max_weight, 1.0)
        else:
            marker_score = 0
        
        return marker_score, found_markers
    
    def detect_watermarks(self, text: str) -> Tuple[bool, List[Dict]]:
        """
        Расширенное обнаружение водяных знаков с извлечением кодов
        """
        found_watermarks = []
        
        for pattern, description in self.watermark_patterns:
            matches = re.finditer(pattern, text, re.IGNORECASE)
            for match in matches:
                code = None
                if match.groups():
                    code = match.group(1) if match.group(1) else None
                    if 'GPT' in description and code:
                        description = f"GPT-{code}"
                        code = f"GPT-{code}"
                
                if not code:
                    code = match.group(0)
                
                watermark_info = {
                    'pattern': pattern,
                    'description': description,
                    'code': code[:50] if code else None,
                    'full_match': match.group(0)[:50]
                }
                found_watermarks.append(watermark_info)
        
        return len(found_watermarks) > 0, found_watermarks
    
    def analyze_text(self, text: str) -> Dict:
        """
        Комплексный анализ текста
        """
        if not text or len(text.strip()) < 10:
            return {
                'error': 'Текст слишком короткий для анализа (минимум 10 символов)',
                'ai_probability': 0,
                'details': {}
            }
        
        lang = self.detect_language(text)
        
        perplexity = self.analyze_perplexity(text)
        burstiness = self.analyze_burstiness(text)
        repetition = self.analyze_repetition(text)
        entropy = self.analyze_entropy(text)
        vocabulary_richness = self.analyze_vocabulary_richness(text)
        punctuation = self.analyze_punctuation(text)
        
        marker_score, found_markers = self.detect_ai_markers(text, lang)
        has_watermark, watermarks = self.detect_watermarks(text)
        translation_score, translation_indicators = self.analyze_translation_indicators(text)
        
        perplexity_score = max(0, min(1, 1 - (perplexity / self.thresholds['perplexity_high'])))
        burstiness_score = max(0, min(1, 1 - (burstiness / self.thresholds['burstiness_low'])))
        repetition_score = max(0, min(1, repetition / self.thresholds['repetition_high']))
        entropy_score = max(0, min(1, 1 - (entropy / self.thresholds['entropy_low'])))
        vocabulary_score = max(0, min(1, 1 - vocabulary_richness))
        
        weights = {
            'perplexity': 0.20,
            'burstiness': 0.15,
            'repetition': 0.15,
            'entropy': 0.15,
            'vocabulary': 0.10,
            'markers': 0.15,
            'punctuation': 0.05,
            'translation': 0.05
        }
        
        watermark_bonus = 0.25 if has_watermark else 0
        translation_penalty = translation_score * 0.1
        
        ai_probability = (
            perplexity_score * weights['perplexity'] +
            burstiness_score * weights['burstiness'] +
            repetition_score * weights['repetition'] +
            entropy_score * weights['entropy'] +
            vocabulary_score * weights['vocabulary'] +
            marker_score * weights['markers'] +
            (1 - punctuation) * weights['punctuation'] +
            translation_score * weights['translation']
        ) + watermark_bonus - translation_penalty
        
        ai_probability = max(0, min(1.0, ai_probability))
        
        if translation_score > 0.3:
            ai_probability = ai_probability * (1 - translation_score * 0.2)
        
        details = {
            'language': lang,
            'perplexity': round(perplexity, 2),
            'perplexity_score': round(perplexity_score, 3),
            'burstiness': round(burstiness, 3),
            'burstiness_score': round(burstiness_score, 3),
            'repetition': round(repetition, 3),
            'repetition_score': round(repetition_score, 3),
            'entropy': round(entropy, 3),
            'entropy_score': round(entropy_score, 3),
            'vocabulary_richness': round(vocabulary_richness, 3),
            'vocabulary_score': round(vocabulary_score, 3),
            'punctuation_diversity': round(punctuation, 3),
            'ai_markers_score': round(marker_score, 3),
            'ai_markers_found': len(found_markers),
            'ai_markers_list': found_markers[:15],
            'translation_score': round(translation_score, 3),
            'translation_indicators': translation_indicators[:5],
            'has_watermark': has_watermark,
            'watermarks_found': watermarks[:10],
            'word_count': len(text.split()),
            'character_count': len(text),
            'avg_sentence_length': round(statistics.mean([len(s.split()) for s in re.split(r'[.!?]+', text) if s.strip()]), 1)
        }
        
        return {
            'ai_probability': round(ai_probability * 100, 1),
            'probability_level': self._get_probability_level(ai_probability),
            'details': details
        }
    
    def analyze_entropy(self, text: str) -> float:
        """Анализ энтропии"""
        words = text.lower().split()
        if len(words) < 5:
            return 0
        
        freq = Counter(words)
        total = len(words)
        
        entropy = 0
        for count in freq.values():
            prob = count / total
            entropy -= prob * math.log2(prob)
        
        return entropy
    
    def analyze_punctuation(self, text: str) -> float:
        """Анализ пунктуации"""
        total_chars = len(text)
        if total_chars == 0:
            return 0
        
        punctuation = re.findall(r'[.,!?;:]', text)
        punc_ratio = len(punctuation) / total_chars
        
        unique_punc = set(punctuation)
        diversity = len(unique_punc) / 5
        
        return punc_ratio * diversity
    
    def _get_probability_level(self, probability: float) -> str:
        """Определение уровня вероятности с учетом нюансов"""
        if probability < 0.15:
            return 'Очень низкая (написан человеком)'
        elif probability < 0.30:
            return 'Низкая (вероятно, человек)'
        elif probability < 0.50:
            return 'Средняя (возможно смешанный/переводной)'
        elif probability < 0.70:
            return 'Повышенная (вероятно, ИИ с пост-редактированием)'
        elif probability < 0.85:
            return 'Высокая (вероятно, ИИ)'
        else:
            return 'Очень высокая (почти точно ИИ)'


def print_report(result: Dict, filename: str = None):
    """
    Улучшенное отображение отчета с деталями водяных знаков
    """
    print("\n" + "=" * 90)
    print("📊 ОТЧЕТ ПО АНАЛИЗУ ТЕКСТА НА ПРИЗНАКИ ИИ")
    print("=" * 90)
    
    if filename:
        print(f"📁 Файл: {filename}")
    
    print(f"⏰ Время анализа: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("-" * 90)
    
    if 'error' in result:
        print(f"❌ ОШИБКА: {result['error']}")
        print("=" * 90)
        return
    
    # Основные результаты
    print(f"\n🎯 ВЕРОЯТНОСТЬ ИИ: {result['ai_probability']}%")
    print(f"📈 Уровень: {result['probability_level']}")
    
    # Прогресс-бар
    prob = result['ai_probability'] / 100
    bar_length = 50
    filled = int(bar_length * prob)
    bar = '█' * filled + '░' * (bar_length - filled)
    print(f"\n   [{bar}] {result['ai_probability']}%")
    
    print("\n" + "-" * 90)
    print("📋 ДЕТАЛЬНЫЙ АНАЛИЗ:")
    print("-" * 90)
    
    details = result['details']
    
    # Основные метрики
    metrics = [
        ('Язык', details.get('language', 'N/A'), ''),
        ('Количество слов', details.get('word_count', 0), ''),
        ('Количество символов', details.get('character_count', 0), ''),
        ('Средняя длина предложения', details.get('avg_sentence_length', 0), 'сл.'),
    ]
    
    for label, value, extra in metrics:
        print(f"  • {label:28} : {value} {extra}")
    
    # Метрики с оценкой
    print("\n  📊 Статистические показатели:")
    scored_metrics = [
        ('Перплексия', details.get('perplexity', 0), details.get('perplexity_score', 0)),
        ('Всплески (burstiness)', details.get('burstiness', 0), details.get('burstiness_score', 0)),
        ('Повторяемость', details.get('repetition', 0), details.get('repetition_score', 0)),
        ('Энтропия', details.get('entropy', 0), details.get('entropy_score', 0)),
        ('Богатство словаря', details.get('vocabulary_richness', 0), details.get('vocabulary_score', 0)),
        ('Маркеры ИИ', details.get('ai_markers_score', 0), f"найдено: {details.get('ai_markers_found', 0)}"),
    ]
    
    for label, value, score in scored_metrics:
        if isinstance(score, (int, float)):
            if score > 0.6:
                indicator = "🔴"
            elif score > 0.3:
                indicator = "🟡"
            else:
                indicator = "🟢"
        else:
            indicator = "⚪"
        
        score_str = f"(скop: {score})" if isinstance(score, (int, float)) else f"({score})"
        print(f"    {indicator} {label:26} : {value:6.3f} {score_str}")
    
    # Маркеры ИИ
    markers = details.get('ai_markers_list', [])
    if markers:
        print(f"\n  🔍 Найденные маркеры ИИ ({len(markers)}):")
        for i, marker in enumerate(markers[:10], 1):
            print(f"    {i:2}. {marker}")
        if len(markers) > 10:
            print(f"    ... и еще {len(markers) - 10}")
    
    # Водяные знаки с кодами
    watermarks = details.get('watermarks_found', [])
    if watermarks:
        print(f"\n  💧 ВОДЯНЫЕ ЗНАКИ НАЙДЕНЫ ({len(watermarks)}):")
        print("  " + "-" * 80)
        for i, wm in enumerate(watermarks[:10], 1):
            desc = wm.get('description', 'Неизвестный')
            code = wm.get('code', '')
            full = wm.get('full_match', '')
            
            print(f"    {i:2}. {desc}")
            if code and code != full:
                print(f"       Код: {code}")
            if full and full != code:
                print(f"       Строка: {full}")
            print()
        if len(watermarks) > 10:
            print(f"    ... и еще {len(watermarks) - 10} водяных знаков")
        print("  " + "-" * 80)
    else:
        print("\n  💧 Водяные знаки: НЕ ОБНАРУЖЕНЫ")
    
    # Признаки перевода
    translation_indicators = details.get('translation_indicators', [])
    translation_score = details.get('translation_score', 0)
    if translation_indicators:
        print(f"\n  🌐 Признаки машинного перевода (скop: {translation_score:.2f}):")
        for indicator in translation_indicators[:5]:
            print(f"    • {indicator}")
    
    print("\n" + "=" * 90)
    
    # Расширенные рекомендации
    prob_value = result['ai_probability']
    has_watermark = details.get('has_watermark', False)
    translation_score = details.get('translation_score', 0)
    
    print("\n💡 РЕКОМЕНДАЦИИ:")
    
    if has_watermark:
        print("  🚨 ОБНАРУЖЕНЫ ВОДЯНЫЕ ЗНАКИ - текст почти точно сгенерирован ИИ")
    
    if translation_score > 0.4:
        print("  🌐 Текст имеет сильные признаки машинного перевода")
        print("  📝 Это может влиять на точность анализа (переводные тексты часто имитируют ИИ)")
    
    if prob_value < 30:
        print("  ✅ Текст, скорее всего, написан человеком")
        print("  📝 Отсутствуют характерные признаки ИИ-генерации")
    elif prob_value < 50:
        print("  ⚠️ Текст имеет некоторые признаки ИИ, но неоднозначно")
        if translation_score > 0.3:
            print("  🔍 Высокая вероятность, что это переводной текст")
            print("  📝 Переводные тексты могут давать ложные срабатывания")
        else:
            print("  🔍 Рекомендуется дополнительный анализ")
    elif prob_value < 75:
        print("  ⚠️ Текст демонстрирует признаки ИИ-генерации")
        if translation_score > 0.3:
            print("  📝 Часть признаков может быть связана с машинным переводом")
        print("  🔍 Рекомендуется проверка другими методами")
    else:
        print("  🚨 Текст с высокой вероятностью сгенерирован ИИ")
        if translation_score > 0.3:
            print("  📝 Учитывая признаки перевода, возможно ИИ + пост-обработка")
        else:
            print("  🔍 Характерные признаки: однообразие структуры, шаблонные фразы")
    
    print("=" * 90 + "\n")


def main():
    """
    Основная функция для запуска из командной строки
    """
    if len(sys.argv) < 2:
        print("❌ ОШИБКА: Укажите путь к файлу с текстом")
        print("\nИспользование:")
        print(f"  python {os.path.basename(__file__)} input_text.txt")
        print(f"  python {os.path.basename(__file__)} input_text.txt --json  # для JSON вывода")
        sys.exit(1)
    
    file_path = sys.argv[1]
    json_output = '--json' in sys.argv
    
    if not os.path.exists(file_path):
        print(f"❌ ОШИБКА: Файл '{file_path}' не найден")
        sys.exit(1)
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            text = f.read()
    except Exception as e:
        print(f"❌ ОШИБКА при чтении файла: {e}")
        sys.exit(1)
    
    if not text.strip():
        print("❌ ОШИБКА: Файл пуст")
        sys.exit(1)
    
    analyzer = AITextAnalyzer()
    result = analyzer.analyze_text(text)
    
    if json_output:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print_report(result, file_path)


if __name__ == "__main__":
    main()

